### ISSUE TITLE
Tracking Issue - M3U8/Fallback Mode support

### ISSUE THREAD

**Issue by information-redacted** [information-redacted/plex-ext-stream#1]
It seems like the original assumption in the README is wrong, and `.m3u8` files do not explicitly require an authentication token after the initial fetch of `start.m3u8` (which itself links to an transcode-session-id-authenticated version of `index.m3u8`).

This issue tracks the implementation of supporting `.m3u8` files in the userscript and server-side.
- [ ] Detection of `start.m3u8` in the userscript
- [ ] Modification of `start.m3u8`-contained link to `index.m3u8` in the userscript
- [ ] Support for `.m3u8` file extension server-side
